package com.caciopee.loganalyzer.analysis;

public enum WorkflowStepType {
    WORKFLOW_START,
    WORKFLOW_END,

    OBJECT_START,
    OBJECT_END,

    STRUCTURE_START,
    STRUCTURE_END,

    RULES_START,
    RULES_END,

    FILTER_START,
    FILTER_END,

    QUERY_PREPARATION,
    QUERY_EXECUTION,
    TEMP_TABLE_USAGE,

    FIELD_MAPPING,
    FIELD_VALUE_READ,
    FIELD_TYPE_DETECTED,
    FIELD_TYPE_CONVERTED,
    FIELD_INSERTED,

    RELATION_DETECTED,
    RELATION_KEY_CREATED,
    RELATION_ATTACHED,

    MANDATORY_CHECK_START,
    MANDATORY_CHECK_ITEM,
    MANDATORY_CHECK_END,

    DATA_LOADING,
    DATA_FILLING,

    SAVE_START,
    SAVE_END,

    MEMORY_CHECK,
    PERFORMANCE_CHECK,

    CHECKPOINT,
    NULL_CONTINUE,

    WARNING,
    ERROR,

    UNKNOWN
}