package com.caciopee.loganalyzer.entity;

public enum LogEventType {

    // ===== WORKFLOW / STRUCTURE =====
    WORKFLOW_LOOP_START,
    WORKFLOW_NEW_INTERFACE_OBJECT,
    WORKFLOW_STRUCTURE_DATA_CALL,
    STRUCTURE_DATA_START,
    STRUCTURE_DATA_END,
    STRUCTURED_OBJECT_ASSEMBLED,

    // ===== REQUEST / EXECUTION =====
    REQUEST_START,
    REQUEST_END,
    DO_SEARCH_START,
    DO_SEARCH_END,
    SEARCH_BY_ROOT_START,
    SEARCH_BY_ROOT_END,
    PREPARE_SEARCH,
    GLOBAL_SEARCH_COMPLETED,

    // ===== ACTION PHASES =====
    BEFORE_LOAD_START,
    BEFORE_LOAD_END,
    LOAD_START,
    LOAD_END,
    SAVE_ACTION_START,
    SAVE_ACTION_END,

    // ===== RULES =====
    RULES_RUNNING,
    RULES_FINISHED,
    RULE_NOT_FOUND,
    RULE_WARNING,
    TRIGGER_MISFIRED,
    AUTOMATIC_PROCESSING_START,
    AUTOMATIC_PROCESSING_END,

    // ===== FILTER / SEARCH / QUERY =====
    SQL_QUERY,
    SQL_QUERY_FINISHED,
    PREPARED_STATEMENT_INFO,
    TEMP_QUERY_USED,
    TEMP_SAVE_DONE,
    SEARCH_ATTRIBUTES_START,
    SEARCH_ATTRIBUTES_QUERY_DONE,
    SEARCH_TO_STRING_MAPPING,
    LOAD_LIST_CHILDS_START,
    LOAD_LIST_CHILDS_QUERY_B1,
    LOAD_LIST_CHILDS_INSERT_TEMP,
    LOAD_LIST_CHILDS_QUERY_B2,
    LOAD_LIST_CHILDS_FILLING,
    LOAD_LIST_CHILDS_TOTAL,
    SEARCH_RESULT_FETCHED,
    ZERO_ROW_FETCHED,

    // ===== CALL / SOURCE =====
    CALL_RUN_RULES_WS,
    CALL_EXECUTE_FILTER_WS,
    CALL_SAVE_WS,
    SAVE_OR_UPDATE_START,
    SAVE_OR_UPDATE_END,

    // ===== PERFORMANCE / OBSERVABILITY =====
    MEMORY_USAGE,
    CHECKPOINT_TRACE,
    PERFORMANCE_MEASURE,
    SLOW_QUERY,
    SLOW_WORKFLOW_STEP,
    THREADING_ENABLED,
    THREADING_SKIPPED,
    THREAD_COMPLETED,
    SESSION_CLOSED,

    // ===== FIELD / MAPPING =====
    FIELD_MAPPING,
    FIELD_VALUE_READ,
    FIELD_CLASS_CODE,
    TYPE_DETECTED,
    TYPE_CONVERSION_START,
    TYPE_CONVERSION_RESULT,
    TYPE_CONVERSION_SUCCESS,
    FIELD_INSERTED,
    QUERY_PARAMETER_DETECTED,

    // ===== RELATIONS / SAVE DETAILS =====
    RELATION_DETECTED,
    RELATION_KEY_CREATED,
    RELATION_ADDED,
    RELATION_DATA_ATTACHED,
    RELATION_DELETE_QUERY,
    RELATION_CHILD_ARRAY_SAVED,
    RELATION_ROOT_ARRAY_SAVED,
    REL_OPERATION_SAVED,
    REMOVE_OBJECTS_TO_DELETE,
    SAVE_INSTANCE_OPERATION,
    SAVE_TOTAL_TIME,

    // ===== MANDATORY CHECKS =====
    MANDATORY_CHECK_START,
    MANDATORY_FIELDS_LIST,
    MANDATORY_FIELD_CHECK,
    MANDATORY_CHECK_END,
    MANDATORY_CHECK_SUCCESS,

    // ===== ERRORS =====
    ERROR_DETAILS,
    PM_MAPPING_ERROR,
    GENERIC_ERROR,
    NULL_CONTINUE,

    // ===== SAVE / PROCESS =====
    PROCESS_CONTENT_SAVE,
    SAVE_START,
    SAVE_END,

    // ===== SERVICE / HUMAN CONTEXT =====
    SERVICE_START,
    SERVICE_END,
    FILTER_START,
    FILTER_END,
    BUSINESS_RESULT,

    // ===== FALLBACK =====
    UNKNOWN
}