package com.caciopee.loganalyzer.analysis.v2;

public enum WorkflowEventType {

    WORKFLOW_START,
    WORKFLOW_END,

    REQUEST_START,
    REQUEST_END,

    RULE_START,
    RULE_END,
    RULE_WARNING,
    RULE_NOT_FOUND,

    BEFORE_LOAD_START,
    BEFORE_LOAD_END,
    LOAD_START,
    LOAD_QUERY,
    LOAD_FILLING,
    LOAD_END,

    FILTER_START,
    FILTER_END,

    SQL_QUERY,
    SQL_EXECUTION_END,
    SQL_RESULT,
    ZERO_RESULT,

    TEMP_QUERY,
    TEMP_SAVE,

    SEARCH_START,
    SEARCH_END,
    SEARCH_BY_ROOT_START,
    SEARCH_BY_ROOT_END,

    MEMORY_USAGE,
    PERFORMANCE,
    SLOW_STEP,

    MULTITHREADING_ENABLED,
    MULTITHREADING_SKIPPED,
    THREAD_COMPLETED,
    SESSION_CLOSED,

    SAVE_PROCESS_CONTENT,
    SAVE_START,
    SAVE_END,
    SAVE_OR_UPDATE_START,
    SAVE_OR_UPDATE_END,
    SAVE_INSTANCE_OPERATION,
    SAVE_RELATION_OPERATION,
    SAVE_TOTAL_TIME,
    RELATION_DELETE,
    RELATION_SAVE,

    AUTOMATIC_PROCESSING,
    CALL_RUN_RULES,
    CALL_EXECUTE_FILTER,
    CALL_SAVE,

    CHECKPOINT,
    SERVICE_START,
    SERVICE_END,

    BUSINESS_INFO,
    TECHNICAL_INFO,
    WARNING,
    ERROR,

    UNKNOWN
}