package com.caciopee.loganalyzer.analysis.v2;

public enum WorkflowEventType {
    WORKFLOW_START,
    WORKFLOW_END,

    REQUEST_START,
    REQUEST_END,

    RULE_START,
    RULE_END,
    RULE_WARNING,
    RULE_NOT_FOUND,
    RULE_DETAIL,

    BEFORE_LOAD_START,
    BEFORE_LOAD_END,
    LOAD_START,
    LOAD_QUERY,
    LOAD_FILLING,
    LOAD_END,

    FILTER_START,
    FILTER_END,

    SQL_QUERY,
    SQL_EXECUTION_END,
    SQL_RESULT,
    ZERO_RESULT,

    TEMP_QUERY,
    TEMP_SAVE,
    TEMP_DELETE,

    SEARCH_START,
    SEARCH_END,
    SEARCH_BY_ROOT_START,
    SEARCH_BY_ROOT_END,

    WS_SEARCH_REG_TRACABILITE,
    WS_FIND_TRACABILITE_ALGESIRAS,
    WS_SEARCH_REG,
    LASTPOINT_REG,
    SCAN_REG,
    EBOOK_REG,
    FIND_TRACABILITE_WS_REG,
    WS_CREATE_AMPX,
    WS_SAVE_AMP,
    WS_INSERT_TRACABILITE_RFID,
    WS_SEARCH_AMP,
    WS_SEARCH_AMP_F,
    SERVICE_PORTUAIRE,

    TRACE_SIZE,
    AMP_VALUE,
    DATE_ACTION,
    CHECKPOINT,

    DUM_DOUANE,
    ICE_NOT_FOUND,
    BAD_REG,
    CHECKSCAN,

    STRUCTURING_LOOP_START,
    NEW_INTERFACE_OBJECT,
    STRUCTURE_DATA_START,
    STRUCTURE_DATA_END,
    STRUCTURING_FIELD_START,
    FIELD_TRIM_REQUIRED,
    FIELD_CLASS_CODE_DETECTED,
    FIELD_VALUE_READ,
    TYPE_CONVERSION_START,
    TYPE_CONVERSION_SUCCESS,
    TYPE_CONVERSION_NULL,
    FINAL_OBJECT_FIELD_PUT,

    RELATION_PRESENT,
    RELATION_ABSENT,
    RELATION_FIRST_ADDED,
    RELATION_KEY_CREATED,
    RELATION_KEY_ATTACHED,
    RELATION_DATA_ATTACHED,
    RELATION_SAVE,
    RELATION_DELETE,

    MANDATORY_CHECK_START,
    MANDATORY_FIELDS_LIST,
    MANDATORY_FIELD_CHECK,
    MANDATORY_CHECK_SUCCESS,
    BUSINESS_KEY_NULL,

    PM_PP_NULL_ERROR,
    ERROR_DETAILS_EXTRACTED,

    MEMORY_USAGE,
    PERFORMANCE,
    SLOW_STEP,
    HIGH_MEMORY_USAGE,

    MULTITHREADING_ENABLED,
    MULTITHREADING_SKIPPED,
    THREAD_COMPLETED,
    SESSION_CLOSED,

    SAVE_PROCESS_CONTENT,
    SAVE_START,
    SAVE_END,
    SAVE_OR_UPDATE_START,
    SAVE_OR_UPDATE_END,
    SAVE_INSTANCE_OPERATION,
    SAVE_RELATION_OPERATION,
    SAVE_TOTAL_TIME,
    DOCUMENT_SAVE,

    AGGREGATION_START,
    AGGREGATION_END,
    RENDERING_RESULT,

    AUTOMATIC_PROCESSING,
    CALL_RUN_RULES,
    CALL_EXECUTE_FILTER,
    CALL_SAVE,

    TRIGGER_FIRED,
    TRIGGER_COMPLETED,
    CACHE_CLEANER,
    JBPM_ASSIGNMENT,

    SERVICE_START,
    SERVICE_END,

    BUSINESS_INFO,
    TECHNICAL_INFO,
    WARNING,
    ERROR,

    UNKNOWN
}